apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: bookinfo
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/productpage"
        backend:
          service:
            name: productpage
            port:
              number: 9080
      - pathType: Prefix
        path: "/static"
        backend:
          service:
            name: productpage
            port:
              number: 9080
      - pathType: Prefix
        path: "/login"
        backend:
          service:
            name: productpage
            port:
              number: 9080
      - pathType: Prefix
        path: "/logout"
        backend:
          service:
            name: productpage
            port:
              number: 9080
      - pathType: Prefix
        path: "/api/v1/products.*"
        backend:
          service:
            name: productpage
            port:
              number: 9080

